---
- name: Run this playbook on localhost
  hosts: local

  tasks:
    - import_tasks: tasks/general.yml
      tags: general

    - import_tasks: tasks/vnc.yml
      tags: vnc

    - name: Reboot system if required
      become: true
      command: shutdown -r now 'Rebooting to complete system upgrade'
        removes=/var/run/reboot-required
