---
- hosts: all

  # become: true

  tasks:
    - name: Allow change of hostname
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '(^preserve_hostname: )false$'
        line: '\1true'

    - name: "Set hostname to {{ vncsvr_hostname }}"
      hostname:
        name: "{{ vncsvr_hostname }}"

    - name: Turn off MOTD news service
      lineinfile:
        path: /etc/default/motd-news
        regexp: '(^ENABLED=)1$'
        line: '\10'

    - name: Set login banner
      template:
        src: motd.txt
        dest: /etc/motd

    - name: Update apt cache
      apt:
        force_apt_get: yes
        update_cache: yes

    - name: Upgrade all packages
      apt:
        force_apt_get: yes
        name: "*"
        state: latest

    - name: Install packages
      apt:
        name="{{ item }}"
        state=latest
      with_items: "{{ vncsvr_packages }}"

    - name: Reboot system if required
      command: shutdown -r now 'Rebooting to complete system upgrade'
        removes=/var/run/reboot-required
