---
- name: Run this playbook on localhost
  hosts: local

  tasks:
    - name: Execute block as sudo
      become: true
      block:
        - name: Allow change of hostname
          lineinfile:
            path: /etc/cloud/cloud.cfg
            regexp: '^(?P<a>preserve_hostname: )false$'
            line: '\g<a>true'
            backrefs: yes

        - name: "Set hostname to {{ vncsvr_hostname }}"
          hostname:
            name: "{{ vncsvr_hostname }}"

        - name: Turn off MOTD news service
          lineinfile:
            path: /etc/default/motd-news
            regexp: '^(?P<a>ENABLED=)1$'
            line: '\g<a>0'
            backrefs: yes

        - name: Set login banner
          template:
            src: motd.txt
            dest: /etc/motd

        - name: Update apt cache
          apt:
            force_apt_get: yes
            update_cache: yes

        - name: Upgrade all packages
          apt:
            force_apt_get: yes
            name: "*"
            state: latest

        - name: Install packages
          apt:
            name="{{ item }}"
            state=latest
          with_items: "{{ vncsvr_packages }}"

    - name: Execute block as normal user
      block:
        - name: Copy simple file
          template:
            src: simple.txt
            dest: ~/

        - name: Set vnc password
          expect:
            command: vncserver
            responses:
              - (?i)password: "{{ vnc_password }}"
              - (?i)verify: "{{ vnc_password }}"
              - (?i)would you like to enter a view-only password (y/n)?: "n"
            creates: ~/.vnc/xstartup
            no_log: true

    - name: Reboot system if required
      become: true
      command: shutdown -r now 'Rebooting to complete system upgrade'
        removes=/var/run/reboot-required
