---
- hosts: all

  # become: true

  tasks:
    - name: Allow change of hostname
      command: "/bin/sed -i 's/^preserve_hostname: false$/# preserve_hostname: false\npreserve_hostname: true/' /etc/cloud/cloud.cfg"

    - name: "Set hostname to {{ vncsvr_hostname }}"
      hostname:
      name: "{{ vncsvr_hostname }}"

    - name: Turn off MOTD news service
      command: "/bin/sed -i 's/^ENABLED=1$/# ENABLED=1\nENABLED=0/' /etc/default/motd-news"

    - name: Set login banner
      template:
        src: motd.txt
        dest: /etc/motd

    - name: Update apt cache
      apt:
        force_apt_get: yes
        update_cache: yes

    - name: Upgrade all packages
      apt:
        force_apt_get: yes
        name: "*"
        state: latest

    - name: Install packages
      apt:
        name="{{ item }}"
        state=latest
      with_items: "{{ vncsvr_packages }}"

    - name: Reboot system if required
      command: shutdown -r now 'Rebooting to complete system upgrade'
        removes=/var/run/reboot-required
