---
- hosts: all

  # become: true

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install packages
      apt: name={{ item }} state=latest
      with_items: "{{ vncsvr_packages }}"
