---
- name: Execute block as sudo
  become: yes
  block:
    - name: Install packages to build gnucash
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        install_recommends: no
      with_items: "{{ gnucash_build_packages }}"

    - name: Make gnucash directories
      file:
        path: "/gnucash-3.4/{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - SOURCE
        - BUILD

    - name: Download gnucash source
      get_url: 
        url: https://github.com/Gnucash/gnucash/releases/download/3.4/gnucash-3.4.tar.bz2
        dest: /gnucash-3.4/

    - name: Extract gnucash source
      unarchive: 
        src: /gnucash-3.4/gnucash-3.4.tar.bz2
        dest: /gnucash-3.4/SOURCE/
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /gnucash-3.4/SOURCE/CMakeLists.txt

    - name: Modify gnucash_core.i
      vars:
        file_path: /gnucash-3.4/SOURCE/bindings/python/gnucash_core.i
      block:
        - name: Modify gnucash_core.i -- insert temporary markers
          lineinfile:
            path: "{{ file_path }}"
            insertafter: "{{ item.insertafter }}"
            line: "{{ item.line }}"
          with_items:
            - insertafter: '#include "Account.h"'
              line: '~~~ MARKER 1 ~~~'
            - insertafter: '%include <Account.h>'
              line: '~~~ MARKER 2 ~~~'
        - name: Modify gnucash_core.i -- insert block 1
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 1 ~~~'
            line: "{{ item }}"
          with_items:
            - '/* BEGIN ANSIBLE MANAGED BLOCK 1 */'
            - '#include "gnc-budget.h"'
            - '/* END ANSIBLE MANAGED BLOCK 1 */'
        - name: Modify gnucash_core.i -- insert block 2
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 2 ~~~'
            line: "{{ item }}"
          with_items:
            - '/* BEGIN ANSIBLE MANAGED BLOCK 2 */'
            - '%include <gnc-budget.h>'
            - '/* END ANSIBLE MANAGED BLOCK 2 */'
        - name: Modify gnucash_core.i -- remove temporary markers
          lineinfile:
            path: "{{ file_path }}"
            line: "{{ item }}"
            state: absent
          with_items:
            - '~~~ MARKER 1 ~~~'
            - '~~~ MARKER 2 ~~~'

    - name: Modify gnucash_core.py
      vars:
        file_path: /gnucash-3.4/SOURCE/bindings/python/gnucash_core.py
      block:
        - name: Modify gnucash_core.py -- insert temporary markers
          lineinfile:
            path: "{{ file_path }}"
            insertafter: "{{ item.insertafter }}"
            line: "{{ item.line }}"
          with_items:
            - insertafter: "    _new_instance = 'xaccMallocAccount'"
              line: '~~~ MARKER 1 ~~~'
            - insertafter: "Book.add_method\\('qof_book_increment_and_format_counter', 'increment_and_format_counter'\\)"
              line: '~~~ MARKER 2 ~~~'
            - insertafter: "    Book.get_price_db, GncPriceDB\\)"
              line: '~~~ MARKER 3 ~~~'
            - insertafter: "Account.name = property\\( Account.GetName, Account.SetName \\)"
              line: '~~~ MARKER 4 ~~~'
        - name: Modify gnucash_core.py -- insert block 1
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 1 ~~~'
            line: "{{ item }}"
          with_items:
            - ''
            - '## BEGIN ANSIBLE MANAGED BLOCK 1 ##'
            - 'class GncBudget(GnuCashCoreClass): pass'
            - '## END ANSIBLE MANAGED BLOCK 1 ##'
        - name: Modify gnucash_core.py -- insert block 2
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 2 ~~~'
            line: "{{ item }}"
          with_items:
            - '## BEGIN ANSIBLE MANAGED BLOCK 2 ##'
            - "Book.add_method('gnc_book_lookup_budget_by_guid', 'lookup_budget_by_guid')"
            - "Book.add_method('gnc_book_lookup_budget_by_name', 'lookup_budget_by_name')"
            - "Book.add_method('gnc_book_get_default_budget', 'get_default_budget')"
            - "Book.add_method('gnc_book_get_default_budget_guid', 'get_default_budget_guid')"
            - "Book.add_method('gnc_book_set_default_budget_guid', 'set_default_budget_guid')"
            - '## END ANSIBLE MANAGED BLOCK 2 ##'
        - name: Modify gnucash_core.py -- insert block 3
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 3 ~~~'
            line: "{{ item }}"
          with_items:
            - '## BEGIN ANSIBLE MANAGED BLOCK 3 ##'
            - '#Functions that return GncBudget'
            - 'Book.lookup_budget_by_guid = method_function_returns_instance('
            - '    Book.lookup_budget_by_guid, GncBudget)'
            - 'Book.lookup_budget_by_name = method_function_returns_instance('
            - '    Book.lookup_budget_by_name, GncBudget)'
            - 'Book.get_default_budget = method_function_returns_instance('
            - '    Book.get_default_budget, GncBudget)'
            - '#Functions that return GUID'
            - 'Book.get_default_budget_guid = method_function_returns_instance('
            - '    Book.get_default_budget_guid, GUID)'
            - '## END ANSIBLE MANAGED BLOCK 3 ##'
        - name: Modify gnucash_core.py -- insert block 4
          lineinfile:
            path: "{{ file_path }}"
            insertbefore: '~~~ MARKER 4 ~~~'
            line: "{{ item }}"
          with_items:
            - ''
            - '## BEGIN ANSIBLE MANAGED BLOCK 4 ##'
            - '# GncBudget'
            - "GncBudget.add_methods_with_prefix('gnc_budget_')"
            - ''
            - 'budget_dict =  {'
            - "                    'get_guid' : GUID,"
            - "                    'get_account_period_value' : GncNumeric,"
            - "                    'get_account_period_actual_value' : GncNumeric"
            - '               }'
            - ''
            - 'methods_return_instance(GncBudget, budget_dict)'
            - ''
            - 'GncBudget.name = property( GncBudget.get_name, GncBudget.set_name )'
            - '## END ANSIBLE MANAGED BLOCK 4 ##'
        - name: Modify gnucash_core.py -- remove temporary markers
          lineinfile:
            path: "{{ file_path }}"
            line: "{{ item }}"
            state: absent
          with_items:
            - '~~~ MARKER 1 ~~~'
            - '~~~ MARKER 2 ~~~'
            - '~~~ MARKER 3 ~~~'
            - '~~~ MARKER 4 ~~~'

    - name: Prepare to build gnucash
      command: |
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local
          -DWITH_GNUCASH=ON -DWITH_PYTHON=ON
          -DWITH_AQBANKING=OFF -DWITH_OFX=OFF -DWITH_SQL=OFF
          /gnucash-3.4/SOURCE/
      args:
        chdir: /gnucash-3.4/BUILD

    - name: Make gnucash
      make:
        chdir: /gnucash-3.4/BUILD

    - name: Install gnucash
      make:
        chdir: /gnucash-3.4/BUILD
        target: install

- name: Modify .bashrc
  lineinfile:
    path: ~/.bashrc
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - ""
    - "export PYTHONPATH=/usr/local/lib/python3/dist-packages"
