---
- name: Install packages to build gnucash
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: no
  with_items: "{{ gnucash_build_packages }}"

- name: Download gnucash source
  get_url: 
    url: https://downloads.sourceforge.net/sourceforge/gnucash/gnucash-3.4.tar.bz2
    dest: ~/Downloads/

- name: Extract gnucash source
  unarchive: 
    src: ~/Downloads/gnucash-3.4.tar.bz2
    dest: ~/Downloads/
    remote_src: yes
    creates: ~/Downloads/gnucash-3.4/

- name: Modify CMakeLists.txt
  lineinfile: 
    path: ~/Downloads/gnucash-3.4/CMakeLists.txt
    regex: '^(?P<a>set\(GENERATE_SWIG_WRAPPERS ${BUILDING_FROM_VCS}.*)$'
    line: '  \g<a>'
    backrefs: yes

- name: Continue to modify CMakeLists.txt
  lineinfile: 
    path: ~/Downloads/gnucash-3.4/CMakeLists.txt
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items:
    - { insertafter: '^# By default they will only be generated', line 'if (FORCE_SWIG)' }
    - { insertafter: '^if \(FORCE_SWIG\)', line '  set(GENERATE_SWIG_WRAPPERS "YES")' }
    - { insertafter: '^  set\(GENERATE_SWIG_WRAPPERS "YES"\)', line 'else()' }
    - { insertafter: '^  set\(GENERATE_SWIG_WRAPPERS ${BUILDING_FROM_VCS}', line 'endif()' }

# - name: Prepare to build gnucash
#   command: |
#     cmake -DCMAKE_INSTALL_PREFIX=/usr/local
#       -DWITH_GNUCASH=ON -DWITH_PYTHON=ON -DFORCE_SWIG=ON
#       -DWITH_AQBANKING=OFF -DWITH_OFX=OFF -DWITH_SQL=OFF
#       ~/Downloads/gnucash-3.4

# make
# make install
# sudo make install
