---
- name: Create smb mount credentials
  template:
    src: ./templates/smb/.smbcredentials.template
    dest: ~/.smbcredentials
    mode: 0600

- name: Execute block as sudo
  become: yes
  block:
    - name: Install cifs-utils
      apt:
        name: cifs-utils
        state: latest
        update_cache: yes

    - name: Make smb mount directory
      file:
        path: "{{ smbmount_where }}"
        state: directory
        mode: 0755

    - name: Create smb mount
      templates:
        src: ./templates/smb/smbmount_name.mount.template
        dest:  "/etc/systemd/system/{{ smbmount_name }}.mount"
        mode: 0644

    - name: Make system aware of smb mount
      command: systemctl daemon-reload

    - name: Enable smb mount
      command: "systemctl enable {{ smbmount_name }}.mount"
