---
- name: Execute block as normal user
  block:
    - name: Set vnc server password
      expect:
        command: vncserver :0
        responses:
          (?i)password: "{{ vnc_password }}"
          (?i)verify: "{{ vnc_password }}"
          (?i)would you like to enter a view-only password (y/n)?: "n"
        creates: ~/.vnc/xstartup
      no_log: true

    - name: Stop vnc server process
      command: vncserver -kill :0

    - name: Backup existing xstartup file
      command: mv ~/.vnc/xstartup ~/.vnc/xstartup.bak

    - name: Insert new xstartup file
      copy:
        src: ./vnc/xstartup.template
        dest:  ~/.vnc/xstartup
        mode: 0755

# - name: Execute block as sudo
#   become: true
#   block:
#     - name: Allow change of hostname
#       lineinfile:
#         path: /etc/cloud/cloud.cfg
#         regexp: '^(?P<a>preserve_hostname: )false$'
#         line: '\g<a>true'
#         backrefs: yes
