---
- name: Execute block as normal user
  block:
    - name: Set vnc server password
      expect:
        command: vncserver :0
        responses:
          (?i)password: "{{ vnc_password }}"
          (?i)verify: "{{ vnc_password }}"
          (?i)would you like to enter a view-only password (y/n)?: "n"
        creates: ~/.vnc/xstartup
      # no_log: true
      notify: Stop vnc server process

    - name: Backup existing xstartup file
      command: mv ~/.vnc/xstartup ~/.vnc/xstartup.bak

    - name: Insert new xstartup file
      copy:
        src: ./vnc/xstartup.template
        dest:  ~/.vnc/xstartup
        mode: 0755

- name: Execute block as sudo
  become: true
  block:
    - name: Create vnc service
      template:
        src: ./vnc/vncserver@.service.template
        dest: /etc/systemd/system/vncserver@.service

    - name: Make system aware of vnc service
      command: systemctl daemon-reload

    - name: Enable vnc service
      command: systemctl enable vncserver@0.service
