---
- name: Execute block as sudo
  become: yes
  block:
    - name: Prepare to download vscode
      shell: "{{ item.command }}"
      args:
        warn: no
        # creates: "{{ item.creates }}"
      with_items:
        - { command: 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg',
            creates: '~/microsoft.gpg' }
        - { command: 'install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/',
            creates: '/etc/apt/trusted.gpg.d/microsoft.gpg' }
        - { command: 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list',
            creates: '/etc/apt/sources.list.d/vscode.list' }

    - name: Install vscode
      apt:
        name: code
        # name: code-insiders
        state: latest
        update_cache: yes

    - name: Make vscode files directory
      file:
        path: /usr/share/code
        state: directory
        mode: 0755
      # creates: /usr/share/code/

    - name: Copy files for vscode
      shell: cp /usr/lib/x86_64-linux-gnu/libxcb.so.1* /usr/share/code/
      # creates:
      #   - /usr/share/code//usr/share/code/libxcb.so.1
      #   - /usr/share/code//usr/share/code/libxcb.so.1.1.0

    - name: Edit files for vscode
      lineinfile:
        path: "{{ item }}"
        regexp: '^(?P<a>.*)BIG-REQUESTS(?P<b>.*)$'
        line: '\g<a>_IG-REQUESTS\g<b>'
        backrefs: yes
      with_items:
        - /usr/share/code/libxcb.so.1
        - /usr/share/code/libxcb.so.1.1.0
