---
- name: Execute block as sudo
  become: yes
  block:
    # - name: Prepare to download vscode
    #   shell: "{{ item }}"
    #   args:
    #     warn: no
        # creates: ~/microsoft.gpg
        # creates: /etc/apt/trusted.gpg.d/microsoft.gpg
        # creates: /etc/apt/sources.list.d/vscode.list
    #   with_items:
    #     - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    #     - install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
    #     - echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list

    - name: Prepare to download vscode
      shell: "{{ item.command }}"
      args:
        warn: no
        creates: "{{ item.creates }}"
      with_items:
        - { command: 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg',
            creates: '~/microsoft.gpg' }
        - { command: 'install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/',
            creates: '/etc/apt/trusted.gpg.d/microsoft.gpg' }
        - { command: 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list',
            creates: '/etc/apt/sources.list.d/vscode.list' }

    - name: Install vscode
      apt:
        name: code
        # name: code-insiders
        state: latest
        update_cache: yes

    - name: Make vscode directory
      file:
        path: /usr/share/code
        state: directory
        mode: 0755

    - name: Edit vscode
      shell: cp /usr/lib/x86_64-linux-gnu/libxcb.so.1* /usr/share/code/

    - name: Continue editing vscode
      lineinfile:
        path: /usr/share/code/libxcb.so.1
        regexp: '^(?P<a>.*)BIG-REQUESTS(?P<b>.*)$'
        line: '\g<a>_IG-REQUESTS\g<b>'
        backrefs: yes

    - name: Continue editing vscode
      lineinfile:
        path: /usr/share/code/libxcb.so.1.1.0
        regexp: '^(?P<a>.*)BIG-REQUESTS(?P<b>.*)$'
        line: '\g<a>_IG-REQUESTS\g<b>'
        backrefs: yes
