---
- name: Execute block as sudo
  become: yes
  block:
    - name: Make xfce defaults directory
      file:
        path: /usr/lib/X11/app-defaults
        state: directory
        mode: 0755

    - name: Set xfce defaults
      command: "{{ item }}"
      with_items:
        - cp /etc/xdg/xfce4/panel/default.xml /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
        - cp /etc/X11/app-defaults/XScreenSaver /usr/lib/X11/app-defaults/

    - name: Turn off xscreensaver
      lineinfile:
        path: /usr/lib/X11/app-defaults/XScreenSaver
        regexp: '^(?P<a>\*mode:.*)random$'
        line: '\g<a>off'
        backrefs: yes

- name: Make xfce config directory
  file:
    path: ~/.config/xfce4/xfconf/xfce-perchannel-xml
    state: directory
    mode: 0755

- name: Set desktop background
  copy:
    src: ./templates/xfce/xfce4-desktop.xml.template
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

- name: Set panel autohide
  template:
    src: ./templates/xfce/xfce4-panel.xml.template
    dest: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
